export const MODE = {
    INSERT: "INSERT",
    EDIT: "EDIT",
    VIEW: "VIEW",
    SIMULATION: "SIMULATION",
};

export const CMD = {
    UNDO: "UNDO",
    REDO: "REDO",
    INSERT: "INSERT",
    CLEAR: "CLEAR",
    MOVE: "MOVE",
    SCALE: "SCALE",
    REMOVE_OBJ: "REMOVE_OBJ",
};

export const INSERTABLE_OBJ = {
    WIRE: "WIRE",
    PB_A: "PB_A",
    PB_B: "PB_B",
    LIMIT_A: "LIMIT_A",
    LIMIT_B: "LIMIT_B",
    RELAY: "RELAY",
    R_CONTACT_A: "R_CONTACT_A",
    R_CONTACT_B: "R_CONTACT_B",
    MC: "MC",
    TIMER: "TIMER",
    T_CONTACT_ON_DELAY_A: "T_CONTACT_ON_DELAY_A",
    T_CONTACT_ON_DELAY_B: "T_CONTACT_ON_DELAY_B",
    T_CONTACT_OFF_DELAY_A: "T_CONTACT_OFF_DELAY_A",
    T_CONTACT_OFF_DELAY_B: "T_CONTACT_OFF_DELAY_B",
    LAMP: "LAMP",
    TEXT: "TEXT",
    BASIC: "BASIC",
}